### ISSUE TITLE
想问一下 config中的url_browse对应的是哪个呀，能再具体描述一下么

### ISSUE THREAD

**Issue by Angel007aaa** [liyinchigithub/feishu-robot#1]

**Comment by liyinchigithub** [comment]
url_browse参数值是公司jira浏览项目的路径

例如：公司查看jira bug的地址是 https://jira.homeking.com/browse/S5A-2062

配置信息如下：
```json
"jira": {
		"url": "https://jira.homeking.com",
		"url_browse": "https://jira.homeking.com/browse/",
		"username": "liyc",
		"password": ""
	}
```
示例截图：

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/19643260/167235610-5c2e1c29-3072-4712-8194-d541c59ea26e.png">
