### ISSUE TITLE
Python 3.7.4 运行时报错 发现引入的tasks依赖中的“async” 出错 怎么解决呀

### ISSUE THREAD

**Issue by Angel007aaa** [liyinchigithub/feishu-robot#2]
from . import tasks
E     File "D:\PythonProject\feishu-robot-master\tutorial-env\lib\python3.7\site-packages\asyncio\tasks.py", line 330
E       fs = {async(f, loop=loop) for f in set(fs)}
ill stop working
    from collections import namedtuple, Mapping

**Comment by liyinchigithub** [comment]
依赖问题，解决了吗？

**Comment by Angel007aaa** [comment]
> 问题，解决了吗？
嗯嗯 解决啦；

**Comment by Angel007aaa** [comment]
我在想怎么给他放到服务器上跑、

**Comment by Angel007aaa** [comment]
> 我在想怎么给他放到服务器上跑、

需要打成war包么

**Comment by liyinchigithub** [comment]
python项目，不能想java项目编译打包成jar包或者war包，但可以在服务器上定时任务跑，比如：用shell脚本写一个定时执行python命令

1.创建shell脚本，命名为test.sh
```shell
#!/bin/bash
sudo python main.py \r
echo "执行完毕"
exit 0
```
2.编辑定时任务
```shell
crontab -e
```
3.执行频率为8-23点每小时的第5分钟执行一次
```shell
5 8-23/1 * * * test.sh
```

test.sh 这个shell脚本和项目中main.py 放置在同层级

**Comment by liyinchigithub** [comment]
过段时间会发布一个可视化配置的项目，容器化部署比较易用
